[build]
  base = "client"
  command = "CI=false npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false" 