[build]
  base = "."
  command = "cd client && npm install && npm run build && cd ../server && npm install"
  publish = "client/build"
  functions = "server/functions"

[functions]
  directory = "server/functions"
  node_bundler = "esbuild"
  included_files = ["server/functions/package.json"]
  external_node_modules = ["express", "serverless-http", "multer", "cors", "csv-parse", "csv-stringify"]

[functions.server]
  included_files = ["server/functions/package.json"]
  external_node_modules = ["express", "serverless-http", "multer", "cors", "csv-parse", "csv-stringify"]
  memory = 3008
  timeout = 60

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/.netlify/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=3072"

[dev]
  framework = "#custom"
  targetPort = 3000
  port = 8888
  command = "npm run start"
  publish = "client/build" 