[build]
  base = "."
  command = "npm install && cd server/functions && npm install && cd ../../ && npm run build"
  publish = "client/build"
  functions = "server/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[functions.server]
  included_files = ["server/functions/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400" 