[build]
  base = "."
  command = "npm install && npm run build"
  publish = "build"
  functions = "server/functions"

[functions]
  directory = "server/functions"
  node_bundler = "esbuild"
  included_files = ["server/functions/package.json"]
  external_node_modules = ["express", "serverless-http", "multer", "cors", "csv-parse", "csv-stringify"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false" 