[build]
  base = "/"
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "build"

[[redirects]]
  from = "/analyze"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
  external_node_modules = ["@netlify/functions"]

[functions.server]
  included_files = []
  external_node_modules = []
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, Origin, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
    Vary = "Origin"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=8192" 